config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion:{in:["chinese", "italian", "japanese", "french", "belgian"]}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant.id), notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    # No need for app/views/restaurants/update.html.erb
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :rating, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.save
    if @review.save
      redirect_to @review, notice: "Review was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    # No need for app/views/reviews/update.html.erb
    redirect_to review_path(@review)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    # No need for app/views/reviews/destroy.html.erb
    redirect_to reviews_path, status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, required: false %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"]%>
  <%= f.button :submit%>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div>
  <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>
  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>
  <p>
    <strong>Rating:</strong>
    <%# <%= restaurant.review %>
  </p>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>

<div id="edit_restaurant">
<%= render "form" %>
</div>

<p>
  <%= link_to "Back to restaurants", restaurants_path %>
</p>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<ul class="list-group">
  <% @restaurants.each do |restaurant| %>
  <div> <%= restaurant.name %> </div>
  <div>
    <p><%= restaurant.category %></p>
    <p><%= restaurant.address %></p>
    <% restaurant.reviews.each do |review| %>
    <p><%= reviews.rating %></p>
    <p><%= reviews.content %></p>
    <% end %>
  </div>
  <li><%= link_to(restaurant.name, restaurant_path(restaurant)) %></li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>

<div id="new_restaurant">
<%= render "form" %>
</div>

<p>
  <%= link_to "Back to restaurants", restaurants_path %>
</p>

app/views/restaurants/show.html.erb
<%= render @restaurant %>
<%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %> |
  <%= link_to "Back to restaurants", restaurants_path %>
  <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>

app/views/reviews/_form.html.erb
<%= simple_form_for @review do |f| %>
  <%= f.input :content, required: false %>
  <%= f.input :rating %>
  <%= f.button :submit%>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit review</h1>

<div id="edit_review">
<%= render "form" %>
</div>

<p>
  <%= link_to "Back to restaurant", restaurants/:id %>
</p>

app/views/reviews/new.html.erb
<h1>Create a new review</h1>

<div id="new_review">
<%= render "form" %>
</div>

<p>
  <%= link_to "Back to restaurant", restaurants/:id %>
</p>

app/views/reviews/show.html.erb
<p><strong>Reviews</strong></p>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item"><%= review.content %></li>
  <% end %>
</ul>